language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t bookingportal .
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
