FROM node:14.17.3

LABEL version="1.0"
LABEL description="This is the base docker image for the Digistore Deliveries frontend react app."
LABEL maintainer = ["castro.agbo@ipaygh.com"]

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install 

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]